name: Issue Folder Creation

on:
  issues:
    types: [opened, edited]

jobs:
  create-folder:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.ANDRKRN_MIKIR_APP_ID }}
          private-key: ${{ secrets.ANDRKRN_MIKIR_PRIVATE_KEY }}

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}
          ref: main
          # Make sure the value of GITHUB_TOKEN will not be persisted in repo's config
          persist-credentials: false

      - name: Sanitize issue title
        id: sanitize
        run: |
          echo "SAFE_TITLE=$(echo '${{ github.event.issue.title }}' | tr -cd '[:alnum:]-_')" >> $GITHUB_ENV

      - name: Setup git name
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Handle title change
        if: github.event.action == 'edited'
        run: |
          ISSUE_NUMBER=${{ github.event.issue.number }}
          OLD_TITLE=$(git log -1 --pretty=%B | sed -n "s/.*issue #${ISSUE_NUMBER}: \(.*\)/\1/p")
          NEW_TITLE=$SAFE_TITLE

          if [ "$OLD_TITLE" != "$NEW_TITLE" ]; then
            OLD_FILE="doc/${ISSUE_NUMBER}-${OLD_TITLE}.md"
            NEW_FILE="doc/${ISSUE_NUMBER}-${NEW_TITLE}.md"

            if [ -f "$OLD_FILE" ]; then
              mv "$OLD_FILE" "$NEW_FILE"
              git add "$OLD_FILE" "$NEW_FILE"
              git commit -m "Rename documentation file for issue #${ISSUE_NUMBER}: $NEW_TITLE"
              git push
            fi
          fi

      - name: Create file and commit
        run: |
          ISSUE_NUMBER=${{ github.event.issue.number }}
          ISSUE_TITLE="$SAFE_TITLE"
          ISSUE_BODY="${{ github.event.issue.body }}"
          FOLDER_PATH="doc/${ISSUE_NUMBER}-${ISSUE_TITLE}.md"

          if [ -f "$FOLDER_PATH" ]; then
            echo "File $FOLDER_PATH already exists. Skipping creation."
            exit 0
          fi

          mkdir -p "doc"
          echo "$ISSUE_BODY" > "$FOLDER_PATH"
          git add "$FOLDER_PATH"
          git commit -m "Add documentation file for issue #${ISSUE_NUMBER}: ${{ github.event.issue.title }}"

          git push
